version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - petzi-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - petzi-network

  webhook:
    build:
        context: ./petzi-app
        dockerfile: dockerfile
    container_name: webhook
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - rabbitmq
    networks:
      - petzi-network


  view:
    build:
      context: ./petzi-view
      dockerfile: dockerfile
    container_name: view
    ports:
      - "8080:80"
    networks:
        - petzi-network

volumes:
  postgres_data:

networks:
    petzi-network:
        driver: bridge


