# Generated by Django 4.2.7 on 2023-11-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doors', models.TimeField()),
                ('location_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='buyer_first_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='buyer_last_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='buyer_postcode',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cancellationReason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(default='default event name', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price_currency',
            field=models.CharField(default='CHF', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='promoter',
            field=models.CharField(default='default promoter', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='buyer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook_handler.buyer'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sessions',
            field=models.ManyToManyField(to='webhook_handler.session'),
        ),
    ]
