# Generated by Django 4.2.7 on 2023-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_handler', '0002_buyer_session_remove_ticket_buyer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='cancellationReason',
            new_name='cancellation_reason',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='eventId',
            new_name='event_id',
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
